const projects = [
  {
    _id: 1,
    banner: '/img/TAS-0.png',
    title: 'Tool Algo System',
    gallery: [{ _id: 1, image: '/img/TAS-1.png' }],
    created_with: [{ _id: 1, dev: 'python' }],
    works_on: [
      { _id: 1, action: 'Desktop Application' },
      { _id: 2, action: 'Database Configuration' },
      { _id: 3, action: 'Data Manipulation' },
    ],
    description: 'asdkladaksd <br><br> adads',
  },
  {
    _id: 2,
    banner: '/img/batching0.png',
    title: 'Batching System',
    gallery: [
      { _id: 1, image: '/img/batching1.png' },
      { _id: 2, image: '/img/batching2.png' },
      { _id: 3, image: '/img/batching3.png' },
      { _id: 4, image: '/img/batching4.png' },
      { _id: 5, image: '/img/batching5.png' },
      { _id: 6, image: '/img/batching6.png' },
      { _id: 7, image: '/img/batching7.png' },
      { _id: 8, image: '/img/batching8.png' },
      { _id: 9, image: '/img/batching9.png' },
      { _id: 10, image: '/img/batching10.png' },
      { _id: 11, image: '/img/batching11.png' },
      { _id: 12, image: '/img/batching12.png' },
      { _id: 13, image: '/img/batching13.png' },
      { _id: 14, image: '/img/batching14.png' },
      { _id: 15, image: '/img/batching15.png' },
      { _id: 16, image: '/img/batching16.png' },
      { _id: 17, image: '/img/batching17.png' },
      { _id: 18, image: '/img/batching18.png' },
    ],
    created_with: [
      { _id: 1, dev: 'html' },
      { _id: 2, dev: 'css' },
      { _id: 3, dev: 'bootstrap' },
      { _id: 4, dev: 'javascript' },
      { _id: 5, dev: 'python' },
    ],
    works_on: [
      { _id: 1, action: 'Frontend Developer' },
      { _id: 2, action: 'API Developer' },
      { _id: 3, action: 'Database Management' },
    ],
    description: '',
  },
  {
    _id: 3,
    banner: '/img/COTM-0.png',
    title: 'Centralized Oven Temperature Monitoring',
    gallery: [
      { _id: 1, image: '/img/COTM-1.png' },
      { _id: 2, image: '/img/COTM-2.png' },
    ],
    created_with: [
      { _id: 1, dev: 'html' },
      { _id: 2, dev: 'css' },
      { _id: 3, dev: 'bootstrap' },
      { _id: 4, dev: 'javascript' },
      { _id: 5, dev: 'python' },
    ],
    works_on: [
      { _id: 1, action: 'UI/UX Designer' },
      { _id: 2, action: 'Frontend Developer' },
      { _id: 3, action: 'API Developer' },
      { _id: 4, action: 'Database Management' },
    ],
    description: '',
  },
  {
    _id: 4,
    banner: '/img/MWS-0.png',
    title: 'Material Withdrawal System',
    gallery: [
      { _id: 1, image: '/img/MWS-1.png' },
      { _id: 2, image: '/img/MWS-2.png' },
      { _id: 3, image: '/img/MWS-3.png' },
      { _id: 4, image: '/img/MWS-4.png' },
      { _id: 5, image: '/img/MWS-5.png' },
      { _id: 6, image: '/img/MWS-6.png' },
      { _id: 7, image: '/img/MWS-7.png' },
    ],
    created_with: [
      { _id: 1, dev: 'html' },
      { _id: 2, dev: 'css' },
      { _id: 3, dev: 'bootstrap' },
      { _id: 4, dev: 'javascript' },
      { _id: 5, dev: 'python' },
    ],
    works_on: [
      { _id: 1, action: 'UI/UX Designer' },
      { _id: 2, action: 'Frontend Developer' },
      { _id: 3, action: 'API Developer' },
      { _id: 4, action: 'Database Management' },
    ],
    description: '',
  },
  {
    _id: 5,
    banner: '/img/com-temp-0.png',
    title: 'Community Templates',
    gallery: [
      { _id: 1, image: '/img/com-temp-1.png' },
      { _id: 2, image: '/img/com-temp-2.png' },
    ],
    created_with: [
      { _id: 1, dev: 'html' },
      { _id: 2, dev: 'css' },
      { _id: 3, dev: 'javascript' },
    ],
    works_on: [{ _id: 1, action: 'Frontend Developer' }],
    description: '',
  },
]

export default projects
